[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<*> -<sd_module_test.cpp>
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    vshymanskyy/TinyGSM
    knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson

[env:esp32s3_sdtest]
extends = env:esp32s3
build_src_filter = +<sd_module_test.cpp>
